### PR TITLE
Docker publish and build

### PR DESCRIPTION
**Pull request by peppy**
Accidentally closed #4.

Not merging this just yet, but leaving as a reminder / reason to split things up and use nuget references.

Basically a Dockerfile cannot include things outside its directory, which means that moving the build process inside Dockerfile breaks the multi-project setup.

### CODE REVIEW

**Comment by ThePooN** [comment]
Perhaps it would be better to make a global entrypoint instead that starts the right processor with a specific argument (eg. `mania`), and put Dockerfile at the project root?

edit: wait, isn't it using nuget references already?

**Comment by peppy** [comment]
It is in this PR, yes, but not in master. At the point it is using a reference, it makes less sense for it to be in the same sln as the main processor.

**Comment by ThePooN** [comment]
So we have to remove mania from the main sln.

Should we also create one for mania, although as far as I understand, it would be the only project in the sln? I don't see much point in this but I'm not very experienced in C#.

**Comment by peppy** [comment]
Well, at that point it may be best to split into its own repository. At the time of making it I wasn't sure whether all queue processors would sit in this repo as separate projects, or be split out. I'm still not sure, but all the other ones I've made have been split out for ease of deployment..

**Comment by ThePooN** [comment]
Should I handle splitting them then?

**Comment by peppy** [comment]
it may be best to, yeah. i'm still unsure about having many small git repos (comes with some overhead) but i don't see a better way (multiple sln in one repo sounds weird).

**Comment by peppy** [comment]
I've created an empty repo and given you access https://github.com/ppy/mania-key-ranking-processor

**Comment by ThePooN** [comment]
Perhaps rename it to match the [existing Docker image](https://hub.docker.com/r/pppy/osu-queue-mania-key-rank-processor)?

**Comment by ThePooN** [comment]
Hmm. If you want to reduce git overhead, we can also just set the context of these Docker builds to the project root, rather than sub-project root.

This would be how to build the images:
`docker build -t ppy/osu-queue-mania-key-rank-processor -f osu.Server.Queues.ManiaKeyRankingProcessor/Dockerfile`

That would allow us to continue using git submodules too, if needed (currently used by https://github.com/ppy/osu-difficulty-calculator).

**Comment by peppy** [comment]
That sounds like what I was looking for. That said, if we're going to be doing tag based builds, I think it's best splitting out the repo. I've renamed the repo.

**Comment by peppy** [comment]
Closing this for now. Will be added in the new repo.

**Pull request closed without merging**
